version: '3'
services:
  node:
    container_name: windsock-server
    tty: true
    stdin_open: true
    depends_on: 
      - mongo
    build:
      context: .
      args: 
        - NPM_TOKEN
    env_file: 
      - ./.env
    volumes:
      - .:/var/code:rw
    links: 
      - mongo:mongo
  mongo:
    image: mongo:3.4
    logging:
      driver: 'none'
